version: '2'
services:
  db_dev:
    image: postgres:9.6
    volumes_from:
     - data
    environment:
      POSTGRES_USER: 'imagine'
      POSTGRES_PASSWORD: 'imagine'
      POSTGRES_DB: 'db_imagine_development'
    ports:
      - '5432:5432'
  imagine_dev:
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://imagine:imagine@db_dev:5432/db_imagine_development
    depends_on:
      - db_dev
    links:
      - db_dev
  data:
    image: cogniteev/echo
    command: echo 'Data Container for PostgreSQL'
    volumes:
      - /private/dbdata/psql