version: '2'
services:
  db:
    image: postgres
  imagine:
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/home/app/imagine
      - /home/app/imagine/node_modules
    environment:
      NODE_ENV: production
    depends_on:
      - db